export const REQUEST = 'REQUEST';
export const RECEIVE_BUG_INFO = 'RECEIVE_BUG_INFO';
export const RECEIVE_AUTH_STATUS = 'RECEIVE_AUTH_STATUS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
