// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest
//

#include <pqxx/pqxx>
#include <cppunit/extensions/HelperMacros.h>
#include "backend.h"

auth_response backend::authenticate(const std::string& username, const std::string& password) {
    // to be replaced with checking username & pass against database
    // e.g. SELECT id FROM users WHERE username=$USERNAME AND password=$PASSWORD
    auth_response result;
    result.authed = true;
    result.role = "superadmin";
    result.username = username;

    return result;
}
