#ifndef CONST_H
#define CONST_H
#include <string>

const std::string CONNECTION_DETAILS="dbname=bugtracker user=postgres password=csci222password host=csci222-ass2.cy0af74vuu5h.ap-southeast-2.rds.amazonaws.com";

const std::string DROP_TABLES = "DROP TABLE IF EXISTS TOPDEVELOPERS CASCADE;DROP TABLE IF EXISTS STATISTICS CASCADE;DROP TABLE IF EXISTS COMMENT CASCADE;DROP TABLE IF EXISTS ATTACHMENT CASCADE;DROP TABLE IF EXISTS CCLIST CASCADE;DROP TABLE IF EXISTS DEPENDENCIES CASCADE;DROP TABLE IF EXISTS KEYWORDS CASCADE;DROP TABLE IF EXISTS BUGS CASCADE;DROP TABLE IF EXISTS PROJECT CASCADE;DROP TABLE IF EXISTS USERS CASCADE; DROP TYPE IF EXISTS STATUS CASCADE;DROP TYPE IF EXISTS RANK CASCADE;";

const std::string CREATE_DATABASE = "CREATE TYPE rank AS ENUM('Reporter','Developer','Reviewer','Triager','Superadmin');CREATE TABLE USERS (	username varchar(32) primary key not null,password varchar(128) not null,	email varchar(128) not null unique,privilege_level RANK not null);CREATE TYPE status AS ENUM('UNCONFIRMED','ASSIGNED','FIXED','DUPLICATE','RESOLVED');CREATE TABLE PROJECT(project_name varchar(128) not null,project_id numeric(6) primary key not null);CREATE TABLE BUGS (bug_id numeric(6) primary key not null,creation_ts timestamp not null,delta_ts timestamp not null,	title text not null,short_desc text not null,component text not null,version numeric(6,4) not null,	op_sys text not null,bug_status STATUS not null,dupl_id numeric(6) references BUGS(bug_id) null,bug_file_loc text null,priority numeric(2) null,severity numeric(2) null,	reporter varchar(32) not null references USERS(username) on delete cascade,	assigned_to varchar(32) references USERS(username) null,project_id numeric(6) null references PROJECT(project_id) on delete cascade,votes numeric(8) not null);CREATE TABLE KEYWORDS (bug_id numeric(6) not null references BUGS(bug_id) on delete cascade,word varchar(32) not null,primary key(bug_id, word));CREATE TABLE DEPENDENCIES(bug_id numeric(6) not null references BUGS(bug_id) on delete cascade,dependency numeric(6) not null references BUGS(bug_id) on delete cascade,primary key(bug_id, dependency));CREATE TABLE CCLIST(bug_id numeric(6) not null references BUGS(bug_id) on delete cascade,	username varchar(32) not null references USERS(username) on delete cascade,primary key(bug_id, username));CREATE TABLE ATTACHMENT(attach_id numeric(7) primary key not null,creation_ts timestamp not null,delta_ts timestamp not null,description text not null,	filename text not null,filesize numeric(9) not null,file text not null,attacher varchar(32) not null references USERS(username) on delete cascade);CREATE TABLE COMMENT(comment_id numeric(7) not null,username varchar(32) not null references USERS(username),	bug_id numeric(6) not null references BUGS(bug_id) on delete cascade,creation_ts timestamp not null,body text not null,attach_id numeric(7) references ATTACHMENT(attach_id) null,primary key(comment_id, bug_id));CREATE TABLE STATISTICS(	project_id numeric(6) primary key not null references PROJECT(projecT_id) on delete cascade,num_of_bugs numeric(7) not null,num_of_resolved_bugs numeric(7) not null,total_wait_time numeric(10) not null);CREATE TABLE TOPDEVELOPERS(project_id numeric(6) not null references PROJECT(project_id) on delete cascade,username varchar(32) not null references USERS(username) on delete cascade,	resolved_bugs numeric(7) not null,primary key(project_id, username));";
#endif
