// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "src.h"
#include "controller.h" 
#include "entities.h"

using namespace std; 

std::string src::echo(const std::string& text)
{
    return "Hi, " + text;
}

Rank src::login(const string& username, const string& password){
	Reporter *user;
	Rank result;
	user = get_valid_user(username); //stub
	if (user.get_password()!= password){
		result = 0;
	} else 
		result = user.get_privilege_level();
	
	return result; 
}
