// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "src.h"
#include "controller.h" 
#include "entities.h"

using namespace std; 

std::string src::echo(const std::string& text)
{
    return "Hi, " + text;
}

Rank src::login(const string& username, const string& password){
	Reporter *user;
	Rank value;
	string query = "SELECT FROM USERS * WHERE username='" + username+ "';"
	result r = postgres_non_transaction(query);
	
	result::const_iterator c = r.begin();
	if (c == r.end()){
		value = null;
	} else {
		Reporter user(c[0].as<string>,c[1].as<string>,c[2].as<string>, c[3].as<Rank>);
		if (user.get_password()!= password){
			value = null;
		} else 
			value = user.get_privilege_level();
	}
	return value; 
}
